### ISSUE TITLE
Error when opening the settings window.

### ISSUE THREAD

**Issue by maxklint** [OpenCppCoverage/OpenCppCoveragePlugin#11]
When I click on Tools/Run OpenCppCoverage, a dialog pops out that says "Unknown error".
The version of Visual Studio is 15.4.0 Professional. I got the same error on two different machines.
Standalone OpenCppCoverage.exe x64 v0.9.6.1 works perfectly.

Here is the full exception trace that is printed to the output window:
```
Microsoft.VisualStudio.Composition.CompositionFailedException:

 An exception was thrown while initializing part "Microsoft.VisualStudio.R.Package.Commands.R.VsRTextViewConnectionListener". ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Languages.Editor.Controllers.Views.TextViewConnectionListener..ctor(IServiceContainer services)
   at Microsoft.VisualStudio.R.Package.Commands.R.VsRTextViewConnectionListener..ctor(ICoreShell coreShell)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass53_0.<CreateExport>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.VisualStudio.Composition.NetFxAdapters.MefV1ExportProvider.<>c__DisplayClass12_0.<UnwrapExport>b__1()
   at System.ComponentModel.Composition.Primitives.Export.GetExportedValueCore()
   at System.ComponentModel.Composition.Primitives.Export.get_Value()
   at System.ComponentModel.Composition.ExportServices.GetCastedExportedValue[T](Export export)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValuesCore[T](String contractName)
   at OpenCppCoverage.VSPackage.OpenCppCoveragePackage.GetCoverageViewManager()
   at OpenCppCoverage.VSPackage.OpenCppCoveragePackage.<>c__DisplayClass4_0.<RunCoverage>b__0()
   at OpenCppCoverage.VSPackage.ErrorHandler.<>c__DisplayClass6_0.<Execute>b__0()
   at OpenCppCoverage.VSPackage.ErrorHandler.<ExecuteAsync>d__5.MoveNext()
```

Is that an issue with the plugin or is there something wrong with my installation?

**Comment by OpenCppCoverage** [comment]
Hello,

I have just installed OpenCppCoverage plugin 0.9.4.1 on both Visual Studio 15.4.4 and 15.5.5 and ran it without a problem.

Your error looks like an [MEF](https://msdn.microsoft.com/fr-fr/library/dd460648(v=vs.110).aspx) initialization error. You can try the following things:
 - Clear the MEF cache. For example see [here](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ClearMEFComponentCache) or [here](https://gist.github.com/wellwind/91ef37b15eb22a2992bc)
 - Uninstall / install OpenCppCoverage Plugin if not already done
 - Repair Visual Studio installation if not already done
 - Install Visual Studio module: ``SDK Visual Studio`` and ``Prerequisite for Visual Studio extension developement`` (The exact name of the module can be different as I translated them).

I hope it will help and let me know if it solves or not your issue.

OpenCppCoverage

**Comment by maxklint** [comment]
Hello,

Thanks for the suggestions. Unfortunately, nothing helped.

But now I suspect that the problem is caused by the firewall settings of my work PC on which I did the installation. If the plugin tries to launch the standalone executable and communicate with it through a socket then it is likely to fail in our environment.

Do you think this might be the case judging by the stack trace?

**Comment by OpenCppCoverage** [comment]
Hello,

OpenCppCoveragePlugin does not open network connection.
Do you have similar issue with other plugins?

In your case OpenCppCoverage try to get MEF object in Visual Studio and failed.
Maybe this [link](https://github.com/github/VisualStudio/issues/1340#issuecomment-346887360) (Last message) can help.

OpenCppCoverage

**Comment by maxklint** [comment]
Hello,

Unfortunately, deleting privateregistry.bin and reinstalling did not help either.

I do use several other plugins and none of them has similar issues.

**Comment by OpenCppCoverage** [comment]
Hello,

I created a [new release](https://github.com/OpenCppCoverage/OpenCppCoveragePlugin/releases/tag/0.9.6.0) and with luck, it may solve the issue (I had a strange issue that disappear when increasing the version number of the plugin).

Let me know if you are still interested using OpenCppCoverage plugin as I can provide some basic code that can help debugging your issue.

OpenCppCoverage

**Comment by alexharbold** [comment]
I ran into this same issue at work, disabling R Tools For Visual Studio stopped the error. I was able to recreate the issue at home. This was with the latest version of R Tools 1.3 and the latest version of Open Cpp Coverage Plugin 0.9.6.1

**Comment by tan-wei** [comment]
> 
> 
> I ran into this same issue at work, disabling R Tools For Visual Studio stopped the error. I was able to recreate the issue at home. This was with the latest version of R Tools 1.3 and the latest version of Open Cpp Coverage Plugin 0.9.6.1

Yes, it works with disabling R Tools for VS. Thanks!

**Comment by OpenCppCoverage** [comment]
Hello,

[OpenCppCoverage plugin version 0.9.7.0](https://marketplace.visualstudio.com/items?itemName=OpenCppCoverage.OpenCppCoveragePlugin&ssr=false#overview) fixes this issue.
Feel free to reopen this issue or create a new one if the issue still persist for you.

OpenCppCoverage.
