### ISSUE TITLE
Exception while executing Test-> Run CppCoverage

### ISSUE THREAD

**Issue by g-glowacki** [OpenCppCoverage/OpenCppCoveragePlugin#18]
## Describe your environment
- Version of OpenCppCoverage: 0.9.7.0, Plugin 0.9.4.2 
- Architecture (x86/ x64): x64
- Windows version: Windows 10 Pro
- Visual Studio 2017 Professional 15.7.1

## Describe your problem
Steps to reproduce:
1. Select Test -> Run CppCoverage 

```
Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "Microsoft.VisualStudio.R.Package.Commands.R.VsRTextViewConnectionListener". ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Languages.Editor.Controllers.Views.TextViewConnectionListener..ctor(IServiceContainer services)
   at Microsoft.VisualStudio.R.Package.Commands.R.VsRTextViewConnectionListener..ctor(ICoreShell coreShell)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass53_0.<CreateExport>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.VisualStudio.Composition.NetFxAdapters.MefV1ExportProvider.<>c__DisplayClass12_0.<UnwrapExport>b__1()
   at System.ComponentModel.Composition.Primitives.Export.GetExportedValueCore()
   at System.ComponentModel.Composition.Primitives.Export.get_Value()
   at System.ComponentModel.Composition.ExportServices.GetCastedExportedValue[T](Export export)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValuesCore[T](String contractName)
   at OpenCppCoverage.VSPackage.OpenCppCoveragePackage.GetCoverageViewManager()
   at OpenCppCoverage.VSPackage.OpenCppCoveragePackage.<>c__DisplayClass4_0.<RunCoverage>b__0()
   at OpenCppCoverage.VSPackage.ErrorHandler.<>c__DisplayClass6_0.<Execute>b__0()
   at OpenCppCoverage.VSPackage.ErrorHandler.<ExecuteAsync>d__5.MoveNext()
```

**Comment by g-glowacki** [comment]
Sorry, this was not the Plugin issue, it was from R Tools.

**Comment by OpenCppCoverage** [comment]
Hello,

[OpenCppCoverage plugin version 0.9.7.0](https://marketplace.visualstudio.com/items?itemName=OpenCppCoverage.OpenCppCoveragePlugin&ssr=false#overview) fixes this issue.
Feel free to reopen this issue or create a new one if the issue still persist for you.

OpenCppCoverage.
