### ISSUE TITLE
VS2017 Community Cast Exception

### ISSUE THREAD

**Issue by leleftheriades** [OpenCppCoverage/OpenCppCoveragePlugin#26]
Visual studio 2017, when running OpenCppCoverage for the second time from the context menu of the project in the Solution Explorer. VS 15.9.2 / OpenCpp 0.9.6.1

System.InvalidCastException: Unable to cast object of type 'Microsoft.VisualStudio.Project.VisualC.VCProjectEngine.VCConfigurationShim' to type 'System.__ComObject'.
   at CallSite.Target(Closure , CallSite , Type , Object )
   at OpenCppCoverage.VSPackage.DynamicVCProject.get_Configurations()
   at OpenCppCoverage.VSPackage.ConfigurationManager.ComputeConfiguration(ExtendedProject project, SolutionContext context, String& error)
   at OpenCppCoverage.VSPackage.ConfigurationManager.ComputeConfiguration(SolutionConfiguration2 activeConfiguration, ExtendedProject project, String& error)
   at OpenCppCoverage.VSPackage.ConfigurationManager.GetConfiguration(SolutionConfiguration2 activeConfiguration, ExtendedProject project)
   at OpenCppCoverage.VSPackage.Settings.StartUpProjectSettingsBuilder.ComputeOptionalSettings(SolutionConfiguration2 activeConfiguration, List`1 projects, ExtendedProject project)
   at OpenCppCoverage.VSPackage.Settings.StartUpProjectSettingsBuilder.ComputeOptionalSettings(SolutionConfiguration2 activeConfiguration, ProjectSelectionKind kind)
   at OpenCppCoverage.VSPackage.Settings.StartUpProjectSettingsBuilder.ComputeSettings(ProjectSelectionKind kind)
   at OpenCppCoverage.VSPackage.Settings.UI.MainSettingController.UpdateStartUpProject(ProjectSelectionKind kind)
   at OpenCppCoverage.VSPackage.Settings.MainSettingsManager.ShowSettingsWindows(CoverageRunner coverageRunner, ProjectSelectionKind kind)
   at OpenCppCoverage.VSPackage.OpenCppCoveragePackage.<>c__DisplayClass4_0.<RunCoverage>b__0()
   at OpenCppCoverage.VSPackage.ErrorHandler.<>c__DisplayClass6_0.<Execute>b__0()
   at OpenCppCoverage.VSPackage.ErrorHandler.<ExecuteAsync>d__5.MoveNext()

**Comment by OpenCppCoverage** [comment]
Hello,

I can run several times OpenCppCoverage from the context menu of the project in the Solution Explorer.
Does it happen also if you create a new console application?
Can you try to update to Visual Studio 15.9.7 and reinstall the plugin?

I hope it helps,

OpenCppCoverage

**Comment by leleftheriades** [comment]
Thank you for the reply,
I have updated visual studio and I no longer get the exception
