### ISSUE TITLE
System.OutOfMemoryException when opening the settings window

### ISSUE THREAD

**Issue by Justin-Randall** [OpenCppCoverage/OpenCppCoveragePlugin#46]
I just installed OpenCppCoveragePlugin for Visual Studio 2019. I am using it with a very large project (UnrealEngine with a source build). The entire IDE hangs when going to Tools->Open CPP Coverage Settings. It eventually dies with an OoM exception. The system has 32GB of memory, so this is not as if there is a shortage of RAM avaiable.

```
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Dynamic.ComRuntimeHelpers.CheckThrowException(Int32 hresult, ExcepInfo& excepInfo, UInt32 argErr, String message)
   at CallSite.Target(Closure , CallSite , ComObject )
   at CallSite.Target(Closure , CallSite , Object )
   at OpenCppCoverage.VSPackage.DynamicVCConfiguration..ctor(Object configuration)
   at CallSite.Target(Closure , CallSite , Type , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at CallSite.Target(Closure , CallSite , Type , Object )
   at OpenCppCoverage.VSPackage.DynamicVCProject.get_Configurations()
   at OpenCppCoverage.VSPackage.ConfigurationManager.ComputeConfiguration(ExtendedProject project, SolutionContext context, String& error)
   at OpenCppCoverage.VSPackage.ConfigurationManager.ComputeConfiguration(SolutionConfiguration2 activeConfiguration, ExtendedProject project, String& error)
   at OpenCppCoverage.VSPackage.ConfigurationManager.FindConfiguration(SolutionConfiguration2 activeConfiguration, ExtendedProject project)
   at OpenCppCoverage.VSPackage.Settings.StartUpProjectSettingsBuilder.BuildCppProject(SolutionConfiguration2 activeConfiguration, IConfigurationManager configurationManager, List`1 projects)
   at OpenCppCoverage.VSPackage.Settings.StartUpProjectSettingsBuilder.ComputeOptionalSettings(SolutionConfiguration2 activeConfiguration, List`1 projects, ExtendedProject project)
   at OpenCppCoverage.VSPackage.Settings.StartUpProjectSettingsBuilder.ComputeOptionalSettings(SolutionConfiguration2 activeConfiguration, ProjectSelectionKind kind)
   at OpenCppCoverage.VSPackage.Settings.StartUpProjectSettingsBuilder.ComputeSettings(ProjectSelectionKind kind)
   at OpenCppCoverage.VSPackage.Settings.UI.MainSettingController.UpdateFields(ProjectSelectionKind kind, Boolean displayProgramOutput)
   at OpenCppCoverage.VSPackage.Settings.MainWindowsManager.ConfigureSettingsWindows(ProjectSelectionKind kind, Boolean displayProgramOutput)
   at OpenCppCoverage.VSPackage.Settings.MainWindowsManager.OpenSettingsWindow(ProjectSelectionKind kind)
   at OpenCppCoverage.VSPackage.CommandRunner.<>c__DisplayClass4_0.<OpenSettingsWindow>b__0(MainWindowsManager mainWindowsManager)
   at OpenCppCoverage.VSPackage.CommandRunner.<>c__DisplayClass6_0.<RunCommand>b__0()
   at OpenCppCoverage.VSPackage.ErrorHandler.<>c__DisplayClass6_0.<Execute>b__0()
   at OpenCppCoverage.VSPackage.ErrorHandler.<ExecuteAsync>d__5.MoveNext()
```

**Comment by OpenCppCoverage** [comment]
Thank you for reporting this issue and for contributing to the project.

The project is now being formally retired and the repository will be archived. I am therefore closing all remaining issues, as no further investigation, fixes, or releases are planned.

This administrative closure does not mean that the issue was resolved or that the report was invalid. The discussion will remain available for anyone who wants to address it in a fork.

Thank you for your understanding.
