### ISSUE TITLE
Plugin fails to install

### ISSUE THREAD

**Issue by dingetje** [OpenCppCoverage/OpenCppCoveragePlugin#56]
The plugin fails to install on my system where both VS2013 and VS2022 are installed:

![image](https://user-images.githubusercontent.com/609871/220075323-84f21d9e-4353-41a0-b770-a9175217a371.png)

````
20/02/2023 11:02:57 - Searching for applicable products...
20/02/2023 11:02:57 - Found installed product - Visual Studio Community 2022
20/02/2023 11:02:57 - Found installed product - Global Location
20/02/2023 11:02:58 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

````

**Comment by dingetje** [comment]
[dd_VSIXInstaller_20230220110257_1774.log](https://github.com/OpenCppCoverage/OpenCppCoveragePlugin/files/10783267/dd_VSIXInstaller_20230220110257_1774.log)

**Comment by samerickson** [comment]
It looks like this project has been abandoned. I have found a link from Microsoft about what needs to be done in order to install this plugin on VS2022 (looks like VS2019 and earlier were 32bit and VS2022 is 64bit; that is without reading the whole post): https://learn.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022#extensions-without-running-code

I might create a fork of this and walk through the steps to see if I can get it working again later, as I also need this for a project. If I get it working I will report back.

**Comment by samerickson** [comment]
@dingetje I found a fork of this project where someone has done the work already: https://github.com/h1day/OpenCppCoveragePlugin/releases/tag/for-vs2022

Thanks you @h1day

**Comment by dingetje** [comment]
> @dingetje I found a fork of this project where someone has done the work already: https://github.com/h1day/OpenCppCoveragePlugin/releases/tag/for-vs2022
> 
> Thanks you @h1day

Thanks!

**Comment by dingetje** [comment]
Hmmm...while that version install just fine for VS2022, it fails to detect VS2013

![image](https://user-images.githubusercontent.com/609871/225274893-a9dbd84b-6645-4909-a2dd-eff92d2ad207.png)

**Comment by samerickson** [comment]
@dingetje You should be able to install the official version of the Plugin for VS 2013 and the unofficial for VS 2023. I am curious through why are you stuck using VS 2013? You might be able to get away with locking down the VC toolset used in your .sln configuration. This forces VS to use a specific version of C++ compiler and Visual C++ libraries. If you are using VCPKG this will also need to be applied to your packages by the use of a triplet.

**Comment by OpenCppCoverage** [comment]
Thank you for reporting this issue and for contributing to the project.

The project is now being formally retired and the repository will be archived. I am therefore closing all remaining issues, as no further investigation, fixes, or releases are planned.

This administrative closure does not mean that the issue was resolved or that the report was invalid. The discussion will remain available for anyone who wants to address it in a fork.

Thank you for your understanding.
